### PR TITLE
WIP: Switch to `drawpart`

### PR DESCRIPTION
**Pull request by rohitvarkey**

### CODE REVIEW

**Comment by shashi** [comment]
It's probably time to start looking into adapting Compose3D into Compose. This branch uses Measures.jl and is about to be merged: https://github.com/dcjones/Compose.jl/pull/131

A first step would be to try to use Compose.drawpart, and the Compose ContainerNode types in Compose3D

**Comment by rohitvarkey** [comment]
@shashi The first step is what this PR is trying to achieve. But for 3D, it will need some extra steps like the camera and the lights which are the only modifications in `drawpart` I've made along with the removal of features Compose3D does not currently support like transforms and container promises.

Also lets get Compose3D working on its own nicely first before getting it integrated with Compose. :)

**Comment by rohitvarkey** [comment]
Also the reason why this is a WIP is that it's breaking the rotation and panning ability with the `ThreeJS` backend for some reason. Works fine on master. Been trying to track it down since morning unsuccessfully.

**Comment by rohitvarkey** [comment]
Okay. I ran into the bug again today while messing around with `ThreeJS`. So it's not a Compose3D issue, rather something to do threejs and trackballcontrols with the camera being set to `(0.0, y, 0.0)`. All other coordinates seem to work. I'm going to change the default camera and merge this.

**Pull request merged**
